<ver>21.1</ver>
<efn>C:\Users\adity\Downloads\trial\test.sce</efn>
<author></author>
<con>
<pause>P</pause>
<pause_code></pause_code>
<port1>1</port1>
<quit>Q</quit>
<quit2>0</quit2>
<quit_code></quit_code>
<resume>R</resume>
<resume_code></resume_code>
<send_output>0</send_output>
<start_code></start_code>
<tqcs>130</tqcs>
<tqds>2</tqds>
<tqms>0</tqms>
<tqt>9</tqt>
<tqu>0</tqu>
</con>
<dbi></dbi>
<dbs>button</dbs>
<ddi>0</ddi>
<dds>
<icm_profile></icm_profile>
<orient>0</orient>
<use_icm>0</use_icm>
</dds>
<ddv>Primary Display Driver</ddv>
<depchg>1</depchg>
<discard_windows_messages>0</discard_windows_messages>
<display_status_window>1</display_status_window>
<dmd>32</dmd>
<dmh>1080</dmh>
<dmr>60</dmr>
<dmrf>59.918505784402</dmrf>
<dmw>2560</dmw>
<docs>
<args></args>
<exfl></exfl>
<lfn></lfn>
</docs>
<dp_list></dp_list>
<dsd>C:\Users\adity\Downloads\trial\sounds</dsd>
<dwm>0</dwm>
<dxv>8</dxv>
<efs></efs>
<exclusive_mouse>1</exclusive_mouse>
<exp_version></exp_version>
<exparam>
<man>
<cfg>
<dcfg>
<en>0</en>
<guid>{A4049400-37E8-4968-B530-5FB3895F2FED}</guid>
<name>Default configuration</name>
<r>
<plat>2147483647</plat>
<rd>0</rd>
<ss>0</ss>
</r>
<ss>
<sd></sd>
<sid>-1</sid>
</ss>
</dcfg>
</cfg>
<cs>-1</cs>
<dl>
<grps>
<grp>
<gn></gn>
<pl></pl>
</grp>
</grps>
</dl>
<parms>
<parms></parms>
<ssl></ssl>
</parms>
<pass></pass>
<ssa></ssa>
</man>
</exparam>
<experiment_id></experiment_id>
<font_settings>
<dpi>96</dpi>
<font_smooth>1</font_smooth>
<use_dpi>1</use_dpi>
<use_font_smooth>1</use_font_smooth>
</font_settings>
<ftp>
<ccc>0</ccc>
<do_upload></do_upload>
<host></host>
<id>{ADBC92BE-213A-468D-8F24-A7685D791B0F}</id>
<idle_timeout>0</idle_timeout>
<login_timeout>0</login_timeout>
<mode>0</mode>
<no_upload></no_upload>
<password></password>
<pasv>0</pasv>
<port>21</port>
<remote_dir></remote_dir>
<sync>1</sync>
<testing>0</testing>
<type>0</type>
<upload>0</upload>
<username></username>
</ftp>
<idc>0</idc>
<idt>1000</idt>
<ilc>0</ilc>
<ip_chans></ip_chans>
<lfd>C:\Users\adity\Downloads\trial\</lfd>
<lnb>2</lnb>
<lno>0</lno>
<log>
<append_counter>0</append_counter>
<delimiter>9</delimiter>
<general_list>1</general_list>
<its>0</its>
<meta>0</meta>
<pien>0</pien>
<set_def_file></set_def_file>
<stimulus_list>0</stimulus_list>
<subject_id></subject_id>
<subject_id_pol>0</subject_id_pol>
<video_list>0</video_list>
<warnings>1</warnings>
</log>
<lol>1</lol>
<lpr></lpr>
<lslset>
<col>0</col>
<def></def>
<mod>0</mod>
<name>Presentation</name>
<use>0</use>
</lslset>
<maxpv></maxpv>
<minpv></minpv>
<nam>#==================================================================================#</nam>
<one_processor>2</one_processor>
<oports></oports>
<out_encrypt_key></out_encrypt_key>
<pi_list></pi_list>
<plat>1</plat>
<port_devices></port_devices>
<rdl>
<device>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<saturation>1</saturation>
</abs_axis>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<saturation>1</saturation>
</abs_axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Wheel</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<device_type>2</device_type>
<dx_device_type>18</dx_device_type>
<max_raw_pos>65535</max_raw_pos>
<min_raw_pos>0</min_raw_pos>
<name>Mouse</name>
</device>
<device>
<device_type>3</device_type>
<dx_device_type>19</dx_device_type>
<name>Keyboard</name>
</device>
<device>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<saturation>1</saturation>
</abs_axis>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<saturation>1</saturation>
</abs_axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Wheel</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<device_type>2</device_type>
<dx_device_type>0</dx_device_type>
<max_raw_pos>65535</max_raw_pos>
<min_raw_pos>0</min_raw_pos>
<name>HID-compliant mouse</name>
</device>
<device>
<device_type>3</device_type>
<dx_device_type>0</dx_device_type>
<name>HID Keyboard Device</name>
</device>
<device>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<saturation>1</saturation>
</abs_axis>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<saturation>1</saturation>
</abs_axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Wheel</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<device_type>2</device_type>
<dx_device_type>0</dx_device_type>
<max_raw_pos>65535</max_raw_pos>
<min_raw_pos>0</min_raw_pos>
<name>HID-compliant mouse 1</name>
</device>
<device>
<device_type>3</device_type>
<dx_device_type>0</dx_device_type>
<name>HID Keyboard Device 1</name>
</device>
<device>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<saturation>1</saturation>
</abs_axis>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<saturation>1</saturation>
</abs_axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Wheel</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<device_type>2</device_type>
<dx_device_type>0</dx_device_type>
<max_raw_pos>65535</max_raw_pos>
<min_raw_pos>0</min_raw_pos>
<name>HID-compliant mouse 2</name>
</device>
<device>
<device_type>3</device_type>
<dx_device_type>0</dx_device_type>
<name>HID Keyboard Device 2</name>
</device>
<device>
<device_type>3</device_type>
<dx_device_type>0</dx_device_type>
<name>Standard PS/2 Keyboard</name>
</device>
<device>
<device_type>3</device_type>
<dx_device_type>0</dx_device_type>
<name>HID Keyboard Device 3</name>
</device>
<device>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<saturation>1</saturation>
</abs_axis>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<saturation>1</saturation>
</abs_axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Wheel</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<device_type>2</device_type>
<dx_device_type>0</dx_device_type>
<max_raw_pos>65535</max_raw_pos>
<min_raw_pos>0</min_raw_pos>
<name>HID-compliant mouse 3</name>
</device>
<device>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<saturation>1</saturation>
</abs_axis>
<abs_axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<saturation>1</saturation>
</abs_axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Wheel</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<device_type>2</device_type>
<dx_device_type>0</dx_device_type>
<max_raw_pos>65535</max_raw_pos>
<min_raw_pos>0</min_raw_pos>
<name>PS/2 Compatible Mouse</name>
</device>
<device>
<device_type>4</device_type>
<dx_device_type>17</dx_device_type>
<name>Intel(R) HID Event Filter</name>
</device>
<device>
<device_type>4</device_type>
<dx_device_type>17</dx_device_type>
<name>Intel(R) HID Event Filter 1</name>
</device>
<device>
<device_type>4</device_type>
<dx_device_type>17</dx_device_type>
<name>Converted Portable Device Control device</name>
</device>
<device>
<device_type>4</device_type>
<dx_device_type>17</dx_device_type>
<name>Converted Portable Device Control device 1</name>
</device>
<device>
<device_type>4</device_type>
<dx_device_type>17</dx_device_type>
<name>2.4G Composite Devic</name>
</device>
<device>
<device_type>4</device_type>
<dx_device_type>17</dx_device_type>
<name>USB 2.4G Keyboard</name>
</device>
<device>
<device_type>4</device_type>
<dx_device_type>17</dx_device_type>
<name>USB Receiver</name>
</device>
<device>
<device_type>4</device_type>
<dx_device_type>17</dx_device_type>
<name>USB 2.4G Keyboard 1</name>
</device>
<device>
<device_type>4</device_type>
<dx_device_type>17</dx_device_type>
<name>USB Receiver 1</name>
</device>
<device>
<device_type>4</device_type>
<dx_device_type>17</dx_device_type>
<name>2.4G Composite Devic 1</name>
</device>
<device>
<axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>X-axis</name>
<saturation>1</saturation>
</axis>
<axis>
<dead_zone>0</dead_zone>
<max>1000</max>
<min>-1000</min>
<name>Y-axis</name>
<saturation>1</saturation>
</axis>
<device_type>6</device_type>
<dx_device_type>0</dx_device_type>
<name>gameport device</name>
</device>
<device>
<device_type>9</device_type>
<dx_device_type>0</dx_device_type>
<name>sound device</name>
</device>
<device>
<device_type>13</device_type>
<dx_device_type>0</dx_device_type>
<name>Speech Recognition</name>
<speech>
<engine_class></engine_class>
<lang></lang>
<mc>0</mc>
<prerecord>0</prerecord>
<rw>0</rw>
<sil>200</sil>
<srgs></srgs>
<uwd>0</uwd>
<vocab></vocab>
</speech>
</device>
<device>
<axis>
<max>1000</max>
<min>-1000</min>
<name>x</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>y</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<buts>
<but>
<from>
<states>down;</states>
<type>2</type>
</from>
<max_x>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</max_x>
<max_y>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</max_y>
<min_x>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</min_x>
<min_y>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</min_y>
<name>Pointer Down</name>
<primary></primary>
<to>
<states>down;</states>
<type>5</type>
</to>
</but>
<but>
<from>
<states>down;</states>
<type>5</type>
</from>
<max_x>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</max_x>
<max_y>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</max_y>
<min_x>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</min_x>
<min_y>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</min_y>
<name>Pointer Up</name>
<primary></primary>
<to>
<states>down;</states>
<type>2</type>
</to>
</but>
<but>
<from>
<states>down;</states>
<type>2</type>
</from>
<max_x>
<inc>1</inc>
<origin>2</origin>
<units>1</units>
<used>1</used>
<value>0</value>
</max_x>
<max_y>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</max_y>
<min_x>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</min_x>
<min_y>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</min_y>
<name>Left Down</name>
<primary></primary>
<to>
<states>down;</states>
<type>5</type>
</to>
</but>
<but>
<from>
<states>down;</states>
<type>2</type>
</from>
<max_x>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</max_x>
<max_y>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</max_y>
<min_x>
<inc>0</inc>
<origin>2</origin>
<units>1</units>
<used>1</used>
<value>0</value>
</min_x>
<min_y>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</min_y>
<name>Right Down</name>
<primary></primary>
<to>
<states>down;</states>
<type>5</type>
</to>
</but>
<but>
<from>
<states>down;</states>
<type>2</type>
</from>
<max_x>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</max_x>
<max_y>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</max_y>
<min_x>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</min_x>
<min_y>
<inc>0</inc>
<origin>2</origin>
<units>1</units>
<used>1</used>
<value>0</value>
</min_y>
<name>Top Down</name>
<primary></primary>
<to>
<states>down;</states>
<type>5</type>
</to>
</but>
<but>
<from>
<states>down;</states>
<type>2</type>
</from>
<max_x>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</max_x>
<max_y>
<inc>1</inc>
<origin>2</origin>
<units>1</units>
<used>1</used>
<value>0</value>
</max_y>
<min_x>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</min_x>
<min_y>
<inc>1</inc>
<origin>2</origin>
<units>2</units>
<used>0</used>
<value>0</value>
</min_y>
<name>Bottom Down</name>
<primary></primary>
<to>
<states>down;</states>
<type>5</type>
</to>
</but>
</buts>
<device_type>5</device_type>
<dx_device_type>0</dx_device_type>
<name>pointing device</name>
<uoh>1</uoh>
<upc>0</upc>
<uvt>1</uvt>
</device>
</rdl>
<refchg>1</refchg>
<rep>1</rep>
<require_name_match>1</require_name_match>
<reschg>1</reschg>
<rng>0</rng>
<rts>1</rts>
<sce>
<idv>
<device_type>2</device_type>
<dx_device_type>18</dx_device_type>
<ibn>Button 0</ibn>
<idn>Mouse</idn>
<index>0</index>
<label></label>
<offset>12</offset>
</idv>
<overrides></overrides>
<sfn>all_scenarios</sfn>
</sce>
<sct>
<capture_device>
<abort_on_max_drops>0</abort_on_max_drops>
<bps></bps>
<chan></chan>
<closest_match>0</closest_match>
<closest_match_max></closest_match_max>
<closest_match_min>1, 16, 8000</closest_match_min>
<do_rec_vol>0</do_rec_vol>
<freq></freq>
<ignore_drops>1</ignore_drops>
<max_drops>250</max_drops>
<max_rec_dur>60</max_rec_dur>
<name>None</name>
<rec_vol>1</rec_vol>
<show_drops>1</show_drops>
</capture_device>
<resp_dev>
<combine>0</combine>
<ignore>1000</ignore>
<isr>0</isr>
<md></md>
<mio></mio>
<off_inter>200</off_inter>
<off_thresh>0.02</off_thresh>
<onset_mode>0</onset_mode>
<rec_dur>1000</rec_dur>
<save>0</save>
<thresh>0.2</thresh>
</resp_dev>
</sct>
<sde>
<buffer_length>1000</buffer_length>
<custom_buf>primary</custom_buf>
<default>1</default>
<dup_channels>1</dup_channels>
<ex_period>10</ex_period>
<halt_on_underrun>1</halt_on_underrun>
<max_mix_length>50</max_mix_length>
<min_mix_length>25</min_mix_length>
<mixer>custom</mixer>
<rewind_distance>10</rewind_distance>
<sh_period>0</sh_period>
<side_speakers>1</side_speakers>
<use_rewind_distance>0</use_rewind_distance>
</sde>
<sdv>Primary Sound Driver</sdv>
<show_dis>1</show_dis>
<show_parm>1</show_parm>
<show_term>1</show_term>
<smc>2</smc>
<smd>16</smd>
<smr>44100</smr>
<srs>1</srs>
<sse>
<s>
<a></a>
<ce>1</ce>
<ep>1</ep>
<p>0</p>
</s>
</sse>
<svl>
<attenuation>0</attenuation>
<do_attenuation>0</do_attenuation>
<do_volume>0</do_volume>
<volume>1</volume>
</svl>
<swp>1</swp>
<text_encoding>single_byte</text_encoding>
<trigger_mode>
<cn></cn>
<m>0</m>
<v></v>
<vt>0</vt>
</trigger_mode>
<udt>0</udt>
<unc>#==================================================================================##                                                                                  ##   Paradigm: N400 Sound-spoken word paradigm                                      ##                                                                                  ##   Lab: Language, Memory and Brain Lab                                            ##                                                                                  #</unc>
<upb>0</upb>
<urp>0</urp>
<wob>1</wob>
